name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout optimal-transport
      uses: actions/checkout@v3
      with:
        path: optimal-transport
  
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.5

    - name: Install public dependencies
      shell: bash -l {0}
      run: |
        cd optimal-transport
        pip install -e .

    - name: Run optimal assignment notebook
      shell: bash -l {0}
      run: |
        cd optimal-transport/examples/
        py.test -p no:python --nbval-lax
