name: Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout optimal-transport
      uses: actions/checkout@v3
      with:
        path: optimal-transport

    - name: Install public dependencies
      shell: bash -l {0}
      run: |
        cd optimal-transport
        pip install -e .

    - name: Convert optimal assignment notebook to Python script
      run: jupyter nbconvert --to script examples/optimal_assignment_problem.ipynb

    - name: Run optimal assignment script
      run: python optimal_assignment_problem.py
